directories:
  output: release
  buildResources: build
appId: com.archilya.launcher
productName: Archilya Launcher
publish:
  provider: github
  owner: nebulanovagame
  repo: ArchilyaLauncher
files:
  - filter:
      - dist/**/*
      - dist-electron/**/*
      - package.json
win:
  target: nsis
  icon: public/icon.ico
nsis:
  oneClick: false
  allowToChangeInstallationDirectory: true
  createDesktopShortcut: true
  createStartMenuShortcut: true
  shortcutName: Archilya
electronVersion: 40.0.0
